### ISSUE TITLE
open tcp port as well

### ISSUE THREAD

**Issue by fruch** [sameersbn/docker-bind#13]
it would be nice to add this:
--publish 53:53/tcp

to the quickstart examples
(took me some time to debug why my tcp call to update the DNS weren't working)

**Comment by sameersbn** [comment]
thanks for reported. has been changed.

On Wednesday 11 May 2016 12:18 AM, fruch wrote:
> it would be nice to add this:
> --publish 53:53/tcp
>
> to the quickstart examples
> (took me some time to debug why my tcp call to update the DNS weren't
> working)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sameersbn/docker-bind/issues/13>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAZCI4wv0HsO4DfhSzBn0EfJE7oAbnyAks5qANMJgaJpZM4IbZU7>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com
