### ISSUE TITLE
Restarting (1)

### ISSUE THREAD

**Issue by alizowghi** [sameersbn/docker-bind#15]
Hello

When I run the docker-bind image docker ps says:
Restarting (1) 1 seconds ago

mkdir: cannot create directory '/data/bind': Permission denied

solution:
setenforce 0

**Comment by kevinbader** [comment]
Have you used `chcon -Rt svirt_sandbox_file_t` on your mountpoint, and also used `:z` for the volume binding? Like so:

```
chcon -Rt svirt_sandbox_file_t /myfiles
docker run .... -v /myfiles:/data:z ...
```

**Comment by alizowghi** [comment]
@kevinbader  I used 'chcon -Rt svirt_sandbox_file_t' but without ':z'

My OS was projectatomic and i now use centos 7 and everything is okay with selinux.
