### ISSUE TITLE
Allow custom SSL cert

### ISSUE THREAD

**Issue by zgardner** [sameersbn/docker-bind#18]
When I run webmin, it looks like it is using an SSL cert generated on the fly.
Is there any way a param can be passed to docker to use a SSL cert that I own?

**Comment by jim3ma** [comment]
The ssl cert and key are in `/etc/webmin/miniserv.pem`.

You can mount the /data to volume and update the `/etc/webmin/miniserv.pem`.

**Comment by sameersbn** [comment]
@zgardner does the suggestion of @jim3ma help?

**Comment by lloydwatkin** [comment]
I turned off SSL in webmin, set `referer` key in `/etc/webmin/config` as I am using letsencrypt docker nginx companion

**Comment by XP1** [comment]
I turned off SSL by setting "ssl=0" in `\data\webmin\etc\miniserv.conf`.
