### ISSUE TITLE
Can't access dns server with 'host' command after launching

### ISSUE THREAD

**Issue by necro351** [sameersbn/docker-bind#19]
Hi, after running the container following the tutorial, the host command fails to resolve 'www.google.com'. Also I get an ominous

`WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.`

...warning which is not mentioned in the tutorial.

This is how I run the container:

```
docker run -d --name=bind --dns=127.0.0.1 \
  --publish=172.17.0.1:53:53/udp --publish=172.17.0.1:10000:10000 \
  --volume=/srv/docker/bind:/root/data/bind \
  --env='ROOT_PASSWORD=SecretPassword' \
  sameersbn/bind:latest
```

This is my version and info for docker:
```
root@photon-rps-client [ ~ ]# docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```

```
root@photon-rps-client [ ~ ]# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8
Operating System: VMware Photon/Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 974.9 MiB
Name: photon-rps-client
ID: CEG3:K7XA:UMDZ:HXR4:YEMV:OOIJ:6HIT:4VEJ:JDMM:YLP4:E3EO:KH5V
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

I am running this on Photon OS on Fusion on my Mac:
```
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=13c08b6
```

**Comment by sameersbn** [comment]
@necro351 

Can you test that the DNS server is working by SSH'ing into the VM and running `docker exec -it bind host www.google.com 127.0.0.1`. If it works, then it probably means that you need to open the 53/UDP port on the VM machine in fusion and then use the VM ip address to query the DNS server from the OSX host.

> WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.

this message is new, never noticed it before. but you can ignore it as we know it'll work if the BIND server running inside the container works :wink:

**Comment by necro351** [comment]
There is a similar container that does not have these issues for me at least, perhaps there are some changes that you can cross-patch? It's here:

https://hub.docker.com/r/cosmicq/docker-bind/

...closing this. Thanks.
