### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by rifzy** [sameersbn/docker-bind#20]
hello,

i get this issue when i try to build
(sudo docker build -t sameersbn/bind github.com/sameersbn/docker-bind)
i already install apt-transport-https (sudo apt-get install apt-transport-https)
i just installed docker

here is my source.list
deb http://httpredir.debian.org/debian jessie main
deb-src http://httpredir.debian.org/debian jessie main

deb http://httpredir.debian.org/debian jessie-updates main
deb-src http://httpredir.debian.org/debian jessie-updates main

deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

here is my /etc/apt/sources.list.d/backports.list content
deb http://http.debian.net/debian wheezy-backports main

Get:9 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python2.7-minimal amd64 2.7.6-8ubuntu0.3 [1187 kB]
E: The method driver /usr/lib/apt/methods/https could not be found.
The command '/bin/sh -c rm -rf /etc/apt/apt.conf.d/docker-gzip-indexes  && wget http://www.webmin.com/jcameron-key.asc -qO - | apt-key add -  && echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list  && apt-get update  && DEBIAN_FRONTEND=noninteractive apt-get install -y bind9=${BIND_VERSION}* bind9-host=${BIND_VERSION}* webmin=${WEBMIN_VERSION}*  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by rifzy** [comment]
by the way i run the latest docker version and use virtualbox

**Comment by sameersbn** [comment]
@rifzy sorry for the lateness of my response. have you modified the Dockerfile? Can you share the steps to reproduce this issue?
