### ISSUE TITLE
Allow setting IPv4-mode (or IPv6-mode) only (Or simply allow access to /etc/default/bind9)

### ISSUE THREAD

**Issue by Joshfindit** [sameersbn/docker-bind#21]
Note: this may not be necessary as I'm tracking an issue with either BIND or Docker, but it's part of the configuration for BIND.

The file suggested is `/etc/default/bind9`

**Comment by efficks** [comment]
@Joshfindit I was able to do this simply by passing the "-4" or "-6" argument to the command when starting. The image does not use file `/etc/default/bind9` but simply get it's argument from the command.
