### ISSUE TITLE
mv: failed to access '/data/bind/etc': Too many levels of symbolic links

### ISSUE THREAD

**Issue by Shinigami2so** [sameersbn/docker-bind#28]
I have a problem, after making modifications to my dns server, I need to copy the configs to another server and start the container with the same data I had modified before, I get an error like `mv: failed to access '/data/bind/etc': Too many levels of symbolic links`

**Comment by sameersbn** [comment]
@Shinigami2so please share the steps to reproduce the issue.

**Comment by kerbbles** [comment]
I am now also having this issue. 
I setup the docker and on the initial run everything looked fine, I could get webUI and setup seemed proper.

I then had to reboot the docker host for other reasons and now if when the container will not launch anymore.

I am pushing the volume to an nfs mounted directory in the host. Which is accessible to the host prior to the container launching.

The view log, only says "mv: failed to access '/data/bind/etc': Too many levels of symbolic links" over and over every time it attempts to reboot the container.

Volume setup
/mnt/docker/dns:/data


The nfs mount on the host is
<IP>:/mnt/Store/docker-data:/mnt/docker

so the /mnt/docker is the base dir then the added "dns" sub directory is what is being used to attach the container's /data

from the host I can see the data from the original run
[rancher@rancher ~]$ cd /mnt/docker/dns/
[rancher@rancher dns]$ ls -l
total 8
drwxrwxr-x    3 105      106           4096 Feb  5 02:37 bind
drwxr-xr-x    2 root     root          4096 Feb  5 02:37 webmin
[rancher@rancher dns]$

I can also see the data on my nfs server

Let me know what other information you would liek and I will attempt to obtain it.

Strangly enough, if I modify anything any of the other directories in the mount path, it seems to let this docker load up properly.

**Comment by ryanquinlan** [comment]
Have the same issue. If I point the data volume at the local disk everything is fine. If I put data out on an NFS mount then I get the same error as the OP
