### ISSUE TITLE
Getting a refused with host call

### ISSUE THREAD

**Issue by pnelsonsr** [sameersbn/docker-bind#3]
So I was just setting things up and following your blog out on damagehead and I got to the point of testing and this works.  Here is the reply:
[srv12 ~]$ host www.google.com 172.17.42.1
Using domain server:
Name: 172.17.42.1
Address: 172.17.42.1#53
Aliases:
www.google.com has address 173.194.33.146
www.google.com has address 173.194.33.145
www.google.com has address 173.194.33.144
www.google.com has address 173.194.33.148
www.google.com has address 173.194.33.147
www.google.com has IPv6 address 2607:f8b0:400a:804::1013

and in the logs:
05-May-2015 18:27:14.370 error (network unreachable) resolving 'www.google.com/A/IN': 2001:7fe::53#53

So I then stop and remove the container and change the run command:
from -> --publish=172.17.42.1:53:53/udp
to -> --publish=53:53/udp

and then start it up again.  But this gives me a refused message like:
[srv12 ~]$ host www.google.com 192.168.101.2
Using domain server:
Name: 192.168.101.2
Address: 192.168.101.2#53
Aliases:
Host www.google.com not found: 5(REFUSED)

I tried this coming from other systems as well.  The log shows:
05-May-2015 18:08:25.607 client 192.168.101.2#39475 (www.google.com): query (cache) 'www.google.com/A/IN' denied

So I also tried a specific interface with:
--publish=192.168.101.2:53:53/udp
and I get the same result.  

Is there some config I need to do to get bind to process the request?

**Comment by pnelsonsr** [comment]
I also notice a couple of other things.  

1.  When I use  --publish=53:53/udp or --publish=192.168.101.2:53:53/udp then like I said it get an error with 
host www.google.com 192.168.101.2
but if I do
host www.google.com 172.17.42.1
then it goes through

2. using --publish=10000:10000 or --publish=192.168.101.2:10000:10000 all work for hitting webadmin from external system browsers

I think this is telling me that my configuration for bind is wrong and not letting me to query.  I tried adding an ACL with specific addresses (like 192.168.101.2) and networks (like 192.168.0.0/16), but that didn't work.  I have to admit I really don't understand bind config so I don't know what the heck I'm doing...

**Comment by pnelsonsr** [comment]
must have push closed by accident...

**Comment by pnelsonsr** [comment]
OK I figured out how to do this...
1.  Under "Access Control Lists" I added an ACL named "ournet" with 
192.168.0.0/16
localhost
localnets
2.  Under "Zone Defaults" then under "Default zone settings" section then I changed "Allow queries from.." to "Listed .." and in the edit box I put my ACL "ournet" (w/out quotes).
3.  Saved and then then clicked on "Apply Configuration"
4.  I tested this locally and out in our network and now bind responds.

Now I have to figure out how to do a zone for our network.  Bind is not totally intuitive...

**Comment by pnelsonsr** [comment]
OK got my zones and it is all working...  Cool!

**Comment by sameersbn** [comment]
@pnelsonsr I will revisit my blog post to make sure that the DNS server is accessible over the network.

**Comment by sameersbn** [comment]
@pnelsonsr In reference to your comment https://github.com/sameersbn/docker-gitlab/issues/307#issuecomment-99572908

 I think iptables is not allowing the communication as you would expect. You probably need to do some configuration there.

In my case I use `-p 172.17.42.1:53:53/udp` to make it host only. Then I added some iptables configuration to allow access to the DNS server from any (except `docker0`) interface.

```bash
iptables -A PREROUTING -t nat -p udp -m udp ! -i docker0 --dport 53 -j DNAT --to-destination 172.17.42.1:53
iptables -A FORWARD -p udp -m udp -d 172.17.42.1 --dport 53 -j ACCEPT
```

You also need to open UDP/53 on the incoming interfaces. This rule should be added before any reject rules, else the port will not be opened.
```
# accept UDP/53 connections
iptables -A INPUT -t filter -p udp -m udp --dport 53 -j ACCEPT
```

With this configuration, the DNS server should be accessible from the local networks as well as to the docker containers running on the same host. However one thing to note is that you lose access control with such a configuration.

I am sure with your current configuration you should also be able to get the DNS working for the containers as well with some `iptables` rules without sacrificing the acl options. You probably need to allow DNS queries from the `172.17.42.0/24` network to be accepted by the the `docker0` interface.

I hope this helps.

**Comment by pnelsonsr** [comment]
Thanks @sameersbn!  I'm kinda perplexed by this.  I had set up a second docker bind container on a second system and while testing I noted that when I put the dns ip of the other docker server this did work.  I since have just used this as the default setup (the other docker dns system).  I will look at the iptables suggestions this weekend and see if I can figure this out.

**Comment by pnelsonsr** [comment]
the '-p 172.17.42.1:53:53/udp' in your docker run command?  How do you know the containers IP?

Have you tried this with linking?

**Comment by pnelsonsr** [comment]
Was working on getting docker working with systemd for auto starting at boot.  So, sorry just getting back to this!

So I was trying to figure out what the `-p 172.17.42.1:53:53/udp` in a docker run command would do and how I could possibly know the containers IP prior to running it plus have it be dynamic...  Then I realized that this was the gateway IP of the docker network.  Hmm....

So I tried a little test with
`d run --name=tester --hostname=tester.example.com --dns=172.17.42.1 -it ubuntu bash`
and tried to ping the hostname of the postgresql server and woohoo it worked!  Tried a bunch of hostnames from the bind service to confirm.  

So then I tried I know that is static IP but I checked every docker server and this is the docker network gateway IP address.  So if the bind service is running in a container on the same system it will work with the `--dns=172.17.42.1` no matter what the IP of the bind container is.  Cool!  If the bind container is on another system then put that other systems IP in the `--dns=<>` statement.  

This works for me!  Thanks for send me down the right path!

**Comment by sameersbn** [comment]
@pnelsonsr great! good to know you have it all figured out now. :beers:

**Comment by pnelsonsr** [comment]
Keeping an eye on things!

**Comment by pnelsonsr** [comment]
@sameersbn I was messing around with linking for some other container stuff and I thought that maybe linking might work for my bind-gitlab dns problem (Yeah I know! I already have a solution but if it ain't broke it still might need to be fixed...).  Anyway...

With bind container running, I removing the `--dns=172.17.42.1` option on the gitlab run command and replace it with a `--link=bind:bind` option and this worked as gitlab started normally.  I'm thinking that this is probably the way I want things configured anyway.  Meaning if I have a bind container running on a system then all other local containers should link to that to keep communication on that docker network.

I am also working with docker-compose to get this all working as a group.  Just wanted to share it with you.  Cool stuff!

**Comment by pnelsonsr** [comment]
Well I tried confirming this on another system and it did not work.  I looked at everything that I could think of and can not figure out what is the difference.  Arg...  Thought I had something.  But I think I may have a system that just isn't working correctly.  With the dns option it does work though.

**Comment by pnelsonsr** [comment]
OK so I found the problem with linking and other things...  docker version...  problem system has 1.5.0 and working system has 1.6.0

**Comment by sameersbn** [comment]
@pnelsonsr I don't understand how linking to the bind container gets the DNS resolution working for the gitlab container. It does not make sense to me. Are you sure you have  not added the `--dns` option on the docker daemon?

**Comment by pnelsonsr** [comment]
Yeah I'm using --link withOUT --dns.  I think this is a problem with the version of docker.  All my 1.6.0 versions work fine.  The 1.5.0 systems are problematic.  I'm not willing to try and solve problems with old versions, so I'm going to get these systems updated with 1.6.0 as fast as I can.

**Comment by cyktsai** [comment]
Thank you for your sharing, @pnelsonsr. 
I just encountered the same issue and luckily I found your sharing which solved my problem.

**Comment by pfworks** [comment]
THe other way to do this is to add the following to the options section in named.conf.options
`       allow-recursion { any; };
        allow-query { any; };
        allow-query-cache { any; };
`
You can also set up a named acl and replace "any" with the acl name.

**Comment by blackjackyau** [comment]
pasting a print screen here for someone who missed the apply configuration button like me
![image](https://user-images.githubusercontent.com/4541367/120103691-6d168100-c183-11eb-9695-f9fbe58bdd12.png)
