### ISSUE TITLE
Option to disable IPV6

### ISSUE THREAD

**Issue by Joshfindit** [sameersbn/docker-bind#33]
Within the container, bind seems to always assume IPv6 is enabled.
In the logs, it shows `error (network unreachable) resolving 'xxx.apple.com/A/IN': 2001:500:3::42#53` when there is no IPv6 support outside the container.

As per http://crashmag.net/disable-ipv6-lookups-with-bind-on-rhel-or-centos it states that IPv6 can be disabled by add `OPTIONS="-4"` to `/etc/sysconfig/named` (on centOS)

It would be helpful to either expose the appropriate config to `/data` or have an environment variable that allows it to be disabled.

**Comment by cassman42** [comment]
When I start the container I pass in the -4 as the last option on the command line
Don't know if its "correct" but it seems to work - YMMV...
