### ISSUE TITLE
Unable to start via docker-compose

### ISSUE THREAD

**Issue by liudonghua123** [sameersbn/docker-bind#39]
Hi, I tried with `docker-compose`, but it did not work!

![image](https://user-images.githubusercontent.com/2276718/34554411-bd2fccfe-f167-11e7-8d31-ff374dba000e.png)

**Comment by a-lang** [comment]
Try the latest version, it is working for me.
![docker-bind](https://user-images.githubusercontent.com/11038458/35902936-0efab7fe-0c18-11e8-8248-1ef0c1036e6f.png)
