### ISSUE TITLE
Rereading zone files without...

### ISSUE THREAD

**Issue by pnelsonsr** [sameersbn/docker-bind#4]
I was wondering if you have a way to reread the zone files on a running bind container without webmin -> our zone files are managed in a git repo and installed with a Makefile.  Currently we restart bind.

I would like to just do a command line to tell the bind container to reread.  I thought I would ask you to see if you had done something like that or had any ideas before I set out to compose a way.  Thanks!

**Comment by sameersbn** [comment]
@pnelsonsr send the `HUP` signal to the container `docker kill -s HUP bind` to reload bind.

**Comment by pnelsonsr** [comment]
Oh yeah...  That's perfect!  Just tried it and I see a reload.  I'm glad I asked because I was going down the rndc road.  This is what I hoped for.  Thanks!
