### ISSUE TITLE
Master & Slave docker-bind

### ISSUE THREAD

**Issue by pnelsonsr** [sameersbn/docker-bind#5]
Have you setup a master and slave configuration with docker-bind?  Been reading about it and it looks fairly easy, but thought I'd ask you first because you always seem to have done it all!  Thanks for any info on configuring this.

**Comment by sameersbn** [comment]
@pnelsonsr nah.. I have not done any complicated setup with bind. Just used it to setup a local DNS server and nothing more. I am a n00b when it comes to advanced bind usage.

If you are able to do this, please let me know how its done as well :+1:

**Comment by pnelsonsr** [comment]
We are using docker-bind as our name services environment, so this was the next logical step.  The HUP thing helped a lot, but we have decided that we need to get master slave working so that changes are just done on one bind container and pushed out to all.  OK I am going to work this out.  I'll post my success (failure?) here.

**Comment by bibby** [comment]
I've been battling with this more most of the day. Using identical configurations (contents of `/etc/bind`), my slave will transfer zones from a master when using a fresh vm that installed normally. But with this container, it is not as easy going.

The Webmin will read: *Last transferred : Never* despite *Test Zone Transfer* giving transfers the thumbs up. A db file is created, `/var/lib/bind/{zone}` but has no content. The initial perms on that file are `rw-r--r--` for `root:bind`, but adding group-write permission doesn't seem to help.

**Comment by bibby** [comment]
If I modify `entrypoint.sh` such that it does not remove `/var/lib/bind` nor link that location from the volume ( [these lines](https://github.com/sameersbn/docker-bind/blob/master/entrypoint.sh#L26-L27) ), then my slave finally works.

This offers no persistence for those dbs, making it good for slaves, but poor for other use cases.

**Comment by hjsoliz** [comment]
You could solve this problem just updating the permissions from 755 to 775 on the entrypoint.sh script line 12

**Comment by acaranta** [comment]
I opened a PR #12 that might solve the problem at hand ;)

Can be tested using my build on the hub : acaranta/docker-bind:fix, while the PR is merged/accepted (or not ;) )

**Comment by sameersbn** [comment]
Closing as #12 has been merged. Please re-open if issue persists.
