### ISSUE TITLE
dig error.

### ISSUE THREAD

**Issue by eagleblade** [sameersbn/docker-bind#55]
Why do I have to exec into the server and install dnsutils? should't this be installed from the Dockerfile ?

Testing transfer of slave zone from 172.25.0.4 ..
.. from 172.25.0.4 : Failed : Missing dig command

**Comment by ddiguy** [comment]
I'm not sure, but it looks like you need the dig utility on your client machine.  It's part of the docker container.

**Comment by sameersbn** [comment]
Sorry for the late response. If you are seeing thing message in the webmin ui, then `dnsutils` should be installed. @eagleblade can you please confirm if this is the case?

**Comment by sameersbn** [comment]
This was already resolved in #27
