### ISSUE TITLE
How to work with docker-machine

### ISSUE THREAD

**Issue by secjex** [sameersbn/docker-bind#6]
Hi, thanks for your effort on working this project.

I got the following error from running this container using docker-machine created docker-engine.

I am using MacOS, and docker-machine to create my docker environment(boot2docker with virtualbox)

my boot2docker's ip is `192.168.99.100`

I got this container running on 172.17.0.2(got this info from docker inspect bind)

I can do `nslookup www.google.com 172.17.0.2`

But If I do it on my mac `nslookup www.google.com 192.168.99.100`

I got this

```
Server:		192.168.99.100
Address:	192.168.99.100#53

** server can't find www.google.com: REFUSED
```

Do you have any idea how to resolve this?

**Comment by sameersbn** [comment]
Have not tried this on docker-machine. I will give it a try and let you know.

**Comment by sameersbn** [comment]
Have checked it out, here is my step-by-step guide.

Use docker-machine to create a docker host vm for bind.
```bash
# docker machine create -d virtualbox bind
```

Configure the shell do that docker communicates with the docker host of the bind vm

```bash
# eval "$(/usr/local/bin/docker-machine env bind)"
```

Start the bind container

```bash
# docker run --name bind -itd --restart=always \
  --publish 53:53/udp --publish 10000:10000 \
  --volume /srv/docker/bind:/data \
  sameersbn/bind:latest
```

Query the ip of the bind docker-machine

```bash
# docker-machine ip bind
192.168.99.100
```

Lets try to make a DNS query

```bash
# nslookup www.google.com $(docker-machine ip bind)
Server:   192.168.99.100
Address:  192.168.99.100#53

** server can't find www.google.com: REFUSED
```

This is where you are currently stuck. This has to be resolved in the bind ACL configurations. By default BIND only allows queries from the same network (in this case 172.17.0.0/24). We want it to whitelist queries from other networks as well. To do this open the webmin interface

```bash
xdg-open https://$(docker-machine ip bind):10000
```

This will load the webmin interface in the web browser. Login using the credentials `root/password`.

In the left sidebar, go to **Servers > Bind**.
 - Select **Access Control Lists**
 - Create ACL named `ournet` with `192.168.0.0/16` and **Save**
 
![webmin 1 770 on 5aa3c49e743d ubuntu linux 14 04 3 2015-12-24 12-22-11](https://cloud.githubusercontent.com/assets/410147/11990820/0257fdc4-aa39-11e5-9d07-014a4ec8ce20.png)

- You will be taken back to the BIND module page, Select **Zone Defaults**
- In the **Default zone settings** section change the **Allow queries** option to **listed** and enter `ournet` in the text box.

![webmin 1 770 on 5aa3c49e743d ubuntu linux 14 04 3 2015-12-24 12-26-11](https://cloud.githubusercontent.com/assets/410147/11990880/a25ef98a-aa39-11e5-8700-0e068b96be6f.png)

- Hit **Save** and then **Apply Configuration** link on the top right corner of the screen

Now lets tests the DNS resolution

```bash
# nslookup www.google.com $(docker-machine ip bind)
Server:		192.168.99.100
Address:	192.168.99.100#53

Non-authoritative answer:
Name:	www.google.com
Address: 74.125.23.103
Name:	www.google.com
Address: 74.125.23.99
Name:	www.google.com
Address: 74.125.23.104
Name:	www.google.com
Address: 74.125.23.106
Name:	www.google.com
Address: 74.125.23.147
Name:	www.google.com
Address: 74.125.23.105
```

Thanks to @pnelsonsr to listing this procedure in #3

**Comment by secjex** [comment]
@sameersbn thanks for advice
