### ISSUE TITLE
Not able to run on ubuntu 16.04

### ISSUE THREAD

**Issue by antigenius0910** [sameersbn/docker-bind#60]
Hi Thanks for the awesome project!

I tried your quick start docker run as you mentioned in README.
```
docker run --name bind -d --restart=always \
  --publish 53:53/tcp --publish 53:53/udp --publish 10000:10000/tcp \
  --volume /srv/docker/bind:/data \
  sameersbn/bind:9.11.3-20180713
```

However, due to ubuntu systemd-resolved already occupied 53 on both udp and tcp container fail to start.

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint bind (84714a9b44c7429f35e5a7ce44fcefe2931cfecea213209ad2fca2677f6c85c3): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.
```

```
netstat -tulpn| grep 53
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      5261/systemd-resolv 
udp    28672      0 0.0.0.0:5353            0.0.0.0:*                           820/avahi-daemon: r 
udp     2304      0 127.0.0.53:53           0.0.0.0:*                           5261/systemd-resolv 
udp6       0      0 :::35356                :::*                                820/avahi-daemon: r 
udp6   34560      0 :::5353                 :::*                                820/avahi-daemon: r 
```

I then try disable systemd-resolved.
```
netstat -tulpn| grep 53
udp    28672      0 0.0.0.0:5353            0.0.0.0:*                           820/avahi-daemon: r 
udp6       0      0 :::35356                :::*                                820/avahi-daemon: r 
udp6   34560      0 :::5353                 :::*                                820/avahi-daemon: r 
```

docker container start just fine.
```
docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
04536fe2c60c        sameersbn/bind:9.11.3-20180713   "/sbin/entrypoint.sh…"   3 seconds ago       Up 3 seconds        0.0.0.0:53->53/tcp, 0.0.0.0:10000->10000/tcp, 0.0.0.0:53->53/udp   bind
```

I can see the port being open on host as well
```
bash-3.2# nmap 10.10.0.11
Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-08 22:12 CDT
Nmap scan report for 10.10.0.11
Host is up (0.035s latency).
Not shown: 994 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
53/tcp    open  domain
10000/tcp open  snet-sensor-mgmt
```

However I still got refused.
```
host www.google.com 10.10.0.11
Using domain server:
Name: 10.10.0.11
Address: 10.10.0.11#53
Aliases: 

Host www.google.com not found: 5(REFUSED)
```

If there any steps I missed on configuring? or can anyone point out a good direction for me to troubleshoot?

**Comment by MerNat** [comment]
can u describe how you have disabled the dnsmasq port?

**Comment by michaelblight** [comment]
Same problem here on 17.10. Documented steps here for how far I got and what I tried, in case it helps.

I stopped `systemd-resolved` and was able to start the container. However webmin wouldn't respond (using ip and port). Also I tried `host www.google.com` and got the following:

`;; reply from unexpected source: 127.0.01#53, expected 127.0.0.53#53
`
I edited `/etc/resolv.conf` (outside the container) and changed the nameserver to 127.0.0.1 and restarted the container. Then it could successfully resolve google inside the container but not outside. But webmin was still not responding. I edited `/etc/webmin/miniserv.conf` (inside the container) and changed `ssl=1` to `ssl=0` and that started working.

I followed the instructions [here](https://github.com/sameersbn/docker-bind/issues/3#issuecomment-99262762), and then I could resolve domains outside the container, but only on a different machine.

I have a Windows box at 192.168.0.4, running Ubuntu under VirtualBox at 192.168.0.66. I have multiple docker containers therein that have IP addresses in ranges 172.17.0.* and 172.30.0.*. I pointed my laptop DNS to 192.168.0.66 and VirtualBox/Docker works their magic to get port 53 to 172.17.0.5 (the bind container) such that `host www.google.com` works. Similarly it works from 172.17.0.5. But it doesn't work from any of the other containers or the Ubuntu VM - it gets ` Host www.google.com not found: 2(SERVERFAIL)`.

Then I found [this](https://rendlelabs.com/blog/a-quick-note-on-docker-dns-resolution/) to change the DNS Server for the Docker daemon. That didn't work either, but thinking about it, I didn't check it had an impact on the `/etc/resolv.conf` of the containers, so I should revisit. However, I ran out of time so I took a snapshot and restored.

**Comment by BenKoerber** [comment]
Even better: disable systemd-resolved
`sudo systemctl disable systemd-resolved`

Source: http://manpages.ubuntu.com/manpages/xenial/man8/systemd-resolved.service.8.html

**Comment by green-anger** [comment]
Hi guys. First of all I'm a complete ignoramus in networks. But somehow I've managed to get this docker container working. My settings are
```
Ubuntu Server 18.10
192.168.1.100 - host
172.18.0.111 - bind container
```
As @michaelblight mentioned you need to get `/etc/resolv.conf` edited, but you cannot do it directly (at least on 18.10) as changes will be overwritten (there is a disclaimer). So I appended 
`nameserver 172.18.0.111` to `/etc/resolvconf/resolv.conf.d/head`. I didn't experiment but there are also `base` and `tail` files. I believe the results will be similar just order of statements will differ in the resulting file. With `head` file modified update `/etc/resolv.conf` with `sudo resolvconf -u`.

As @BenKoerber suggested I modified `docker-compose.yml` a bit:
```
ports:
  - "192.168.1.100:10000:10000"
  - "192.168.1.100:53:53/tcp"
  - "192.168.1.100:53:53/udp"
```
That allowed me to keep systemd-resolved running, `netstat -tulpn` produced:
```
udp        0      0 192.168.1.100:53        0.0.0.0:*                           -
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -
```
However I've found people complaining about systemd-resolved so you can disable it as @BenKoerber said. Also see [this link](https://askubuntu.com/a/907249) (has extra steps for 17.04 Zesty).

And I think this is it. I could omit some details as after that I was struggling to get Nginx working and in the end could get confused by overwhelming info. And describing all the struggle would be off topic.
