### ISSUE TITLE
dns_dnssec_findzonekeys2: error reading mydomain.com

### ISSUE THREAD

**Issue by incal** [sameersbn/docker-bind#64]
Hi,
anyone can help me about this problem?:
I have tried many times for some days and with different releases of sameersbin/bind container to make work nsupdate with DNNSEC signature without success.

I have always this kind of error:
"dns_dnssec_findzonekeys2: error reading mydomain.com.+005+27378.private: file not found"

the key files exists but the error persist,

specify "key-directory "/data/bind/lib/"; in named.conf.local or named.conf.options not help

sorry for my English, regards
Maurizio

**Comment by mjeynes** [comment]
I use RHEL7 and `named`.

My `/etc/named.conf` specifies 

`  directory "/var/named";`

So the key and private files go in this directory at `chmod 640` and `chown named:named`

and `systemctl restart named`
