### ISSUE TITLE
Docker Container Crashes immediatly on Synology NAS

### ISSUE THREAD

**Issue by noaboa97** [sameersbn/docker-bind#69]
Hello,

I've installed this docker container and it crashes immediatly.

Network mode: Hostnetwork

The Log says:
chpasswd: (user root) pam_chauthtok() failed, error:
System error
chpasswd: (line 1, user root) password not changed

**Comment by protvis74** [comment]
Hello,
my docker container also crashed/exited directly after startup on my raspberry pi.
Error:  standard_init_linux.go:207: exec user process caused "exec format error"
I found out that the message you receive is typically architecture related. So the pulled image from the repository is not suited for the armf platform ARMv7 (Raspberry Pi).

Solution: I built a new image from the sources with: 
`docker build -t sameersbn/bind github.com/sameersbn/docker-bind`

After building and creating this new container from source this docker container works without crashing on my raspberry pi. Maybe you have a similar issue.
