### ISSUE TITLE
Error when mounting into /etc/bind

### ISSUE THREAD

**Issue by strarsis** [sameersbn/docker-bind#8]
For modifying the default configuration of bind in image, 
I mount files/folders into the /etc/bind/ directory inside the container.
However, this doesn't seem to work with this bind image:
````
[...]
rm: cannot remove '/etc/bind/testfile': Device or resource busy
bind[...] exited with code 1
````

I prepared a repository with a docker-compose.yml for easily reproducing the issue:
https://github.com/strarsis/bind-issue
````
$ git clone https://github.com/strarsis/bind-issue
$ cd bind-issue
$ docker-compose up
````

It is possible to mount files/folders into container _outside_ of /etc/bind/ without issues, 
bind starts up and runs normally then, but bind config cannot be changed that way though.

Thank you and
with best regards

**Comment by sameersbn** [comment]
@strarsis this is not right. you need to mount a volume at `/data`. All the bind configurations will be available at your host mount point, which can be edited. Please refer the readme for details.

**Comment by strarsis** [comment]
Thank you.
