### ISSUE TITLE
resolve records not precent in internal dns server

### ISSUE THREAD

**Issue by encryptblockr** [sameersbn/docker-bind#87]
i am fully setup with your docker image and now using webmin to manage the dns server
 
i have a created master zone created for a domain that is also publicly available
i have some records that are only internal and some records that are public on the internet using dns servers of a provider

now i want to be able to resolve the internal records but when the record is not available i want it to resolve to external

is this possible?

**Comment by philippe-bourdeau** [comment]
I have the same need. Can we bring this issue up ?

**Comment by philippe-bourdeau** [comment]
@encryptblockr I suggest you look at this issue, it helped me solved the problem:

https://github.com/sameersbn/docker-bind/issues/14
