### ISSUE TITLE
Mounting /data on NFS

### ISSUE THREAD

**Issue by kjenney** [sameersbn/docker-bind#9]
I'm trying to mount /data on an NFS mount. The idea is that I can boot up the image from any of my hosts in case one goes down. However, I'm getting the following error:

```chown: changing ownership of`/data/bind': Operation not permitted

Looks like the directories are initially created by nobody:nogroup. 

Which user is attempting to change theh ownership? 
Is this because of the docker bridge network? 
How can I map /data to my NFS mount.

**Comment by diogogmt** [comment]
I was having the same problem, had to tweak the export and mount settings to fix the issue.

**Comment by rbrenner** [comment]
@diogogmt, what settings on the client/server for your NFS mounts did you use to resolve the issue?

**Comment by hanzou89** [comment]
How solve the issue?
